[2024-02-16 01:37:37,858: INFO: main: >>>>>>>>>> stage Data Ingestion Stage started <<<<<<<<<<]
[2024-02-16 01:37:37,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 01:37:37,858: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\utils\common.py", line 25, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\main.py", line 9, in <module>
    data_ingestion.main()
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\pipeline\stage_01_data_ingestion.py", line 17, in main
    raise e
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\config\configuration.py", line 10, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\utils\common.py", line 27, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
